name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install build dependencies
      run: sudo apt-get install libsdl1.2-dev
  
    - name: Generate configure script and Makefiles
      run: |
        cd $GITHUB_WORKSPACE
        ./bootstrap

    - name: Run configure script
      run: |
        mkdir $GITHUB_WORKSPACE/build
        cd $GITHUB_WORKSPACE/build
        ../configure

    - name: Run make
      run: |
        cd $GITHUB_WORKSPACE/build
        make

    - name: Run make check
      env:
        SYNDICATE_DATA_PATH: ${{env.GITHUB_WORKSPACE}}/test/fixtures
      run: |
        cd $GITHUB_WORKSPACE/build
        make check
